- name: disable default nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs 20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs and mysql client #mysql client to connect to mysql database
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
  - nodejs
  - mysql
  
- name: create expense user #using user module will takes care of idempotency 
  ansible.builtin.user:
    name: expense

- name: import tasks from common role
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: install dependencies
  ansible.builtin.command: npm install #as npm install we need to run in /app directory where package.json is exists we are changing the directory using chdir: /app
  args:
    chdir: /app

- name: Copy backend service #copy only works for files without variables
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: ansible to install pymysql #ansible-server needs PyMySQL to connect to database
  ansible.builtin.pip:
    name:
    - PyMySQL
    - cryptography
    executable: pip3.9

- name: import mysql data #using community module
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ login_host }}"
    target: /app/schema/backend.sql
    name: all
    state: import

- name: daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: backend